"""Export hook for the gear mesh example.

The current viewer preview is generated by refresh_gear_result.mjs. This Python
hook keeps the browser's Abaqus run pipeline complete after an Abaqus solve.
"""

from __future__ import print_function

import os


def main():
    root = os.path.dirname(os.path.abspath(globals().get("__file__", os.getcwd())))
    result_path = os.path.join(root, "result_mesh.json")
    if not os.path.exists(result_path):
        raise RuntimeError("Missing result_mesh.json. Run refresh_gear_result.mjs to create the viewer result.")
    print("Gear mesh viewer result is available: {}".format(result_path))


if __name__ == "__main__":
    main()
